### ISSUE TITLE
Unknown type name 'namespace'

### ISSUE THREAD

**Issue by Klemen1337** [TrustWallet/trezor-crypto-ios#1]
Hi,
I had your library installed and it worked fine. Now for some reason I get an error "Unknown type name 'namespace'" in config.h line 97. Any Idea why this would happen? I'm using xcode 9.3 with swift 4

Cheers,
K

**Comment by alejandro-isaza** [comment]
this happens on the master branch of trezor-crypto, make sure you are not on master but on the submodule hash (`git submodule update`).

**Comment by Klemen1337** [comment]
I installed it via cocoapods. Im not sure how to do that.

**Comment by alejandro-isaza** [comment]
What version are you getting? Try `pod update` if you are not on 0.0.5.

**Comment by Klemen1337** [comment]
I figure it out. I had "CryptoppECC" and "TrezorCrypto" installed and that caused the error.
